Fix: time issue
a-happy-dev-day/yanawa-server pull request #48
Opened 2022-10-28 18:29 UTC by wjdxor

### 문제발생
 LocalTime.now() 라이브러리 메소드를 사용하였더니 현재 시간에 따라 테스트 성공 유무가 바뀌는 문제 발생

서비스 안에 now()가 메서드에 의해 결정되는 상황을 피하기 위한 방법이 필요

### 해결방법
시간 설정 클래스를 만들어 Bean에 저장하여 사용

2022-11-01 07:49 UTC, this-is-spear requested changes
테스트가 실패했네요 ㅜ 
그리고 테스트를 위해 서비스 영역에 설정 파일이 의존되는 건 좋은 방식이 아닌 것 같습니다...!!

2022-11-01 07:49 UTC, this-is-spear commented on src/main/java/fashionable/simba/yanawaserver/configuration/TimeConfig.java
> +    private ZoneOffset zoneOffset = ZoneOffset.of("+09:00");
빈은 동시성 문제가 발생하기 때문에 상태를 가지면 안됩니다. `timeFixed` 메서드에 의해 clock 변수가 변경되고 있는데, 다른 요청에 영향이 갈 것 같아요!

2022-11-01 07:49 UTC, this-is-spear commented on src/main/java/fashionable/simba/yanawaserver/matching/domain/service/MatchingService.java
> +    private final TimeConfig timeConfig;
테스트를 위한 설정 파일이 소스 코드에 의존하면 복잡성도 늘고 관리도 어려울 것 같습니다. 😢

2022-11-03 03:05 UTC, this-is-spear requested changes

2022-11-03 03:05 UTC, this-is-spear commented on src/main/java/fashionable/simba/yanawaserver/configuration/Clock.java
>      }
아직 빈의 상태가 변경이 되고 있습니다 🥺
동시성 이슈가 발생할 위험이 있는데, 변경이 필요해보여요!

2022-11-03 03:07 UTC, this-is-spear commented on src/main/java/fashionable/simba/yanawaserver/configuration/Clock.java
>      }
Clock에서 제공하는 정적 메서드 패턴을 호출해 빈에서 선언된 객체를 재할당하는 상황인데, 동시에 여러 스레드가 접근하는 환경에서는 위험합니다.

2022-11-04 08:36 UTC, wjdxor commented
### 문제
- 매칭 종료시간이 현재 시간보다 뒤인 경우를 테스트할 때
   - 종료 시간을 현재시간 + 1시간으로 설정
   - 이 경우, 자정을 지나 종료시간이 다음날로 설정 되는 경우가 있다.
   - 이 때, 매칭 시작시간보다 종료시간이 빨라 매칭 생성이 안되는 에러가 발생
 ### 해결
- 현재시간을 Mocking 한다.
   - 현재 시간을 설정파일로 만들어 서비스레이어에서 이 설정파일에 의존 해야한다.
- 매칭 생성할 때 날짜와 시간을 계산한다.
   - 기획 단계에서 날짜를 넘어가는 매칭은 없다고 생각하였기때문에 매칭 정보로 
      날짜(LocalDate), 시작시간(LocalTime), 종료시간(LocalTime) 을 저장한다.
      날짜와 시간을 같이 계산하기 위해선 도메인 설계 수정이 필요해 보인다.

2022-11-04 08:36 UTC, closed without merging